### PR TITLE
fix NullPointerException raised when checking 'ignoreWhiteSpaces'

### LINKED ISSUE #1838: [cygnus-ngsi][bug][NGSIElasticsearchSink] raises NullPointerException when checking 'ignoreWhiteSpaces'
NGSIElasticsearchSink raises the NullPointerException when `ignore_white_spaces` is `true` and an attribute has `null` value.

When I sent a message like below, NGSIElasticsearchSink raised a NullPointerException.

```json:message
{
  "subscriptionId": "5d64c7d48e7ee6dc2b62c21c",
  "originator": "localhost",
  "contextResponses": [
    {
      "contextElement": {
        "type": "Unibo",
        "isPattern": "false",
        "id": "urn:ngsi-ld:Unibo:1",
        "attributes": [
          {
            "name": "Alert_info",
            "type": "commandResult",
            "value": " "
          },
          {
            "name": "Alert_status",
            "type": "commandStatus",
            "value": "PENDING",
            "metadatas": [
              {
                "name": "TimeInstant",
                "type": "DateTime",
                "value": "2019-08-28T01:44:17.00Z"
              }
            ]
          },
          {
            "name": "Connect_info",
            "type": "commandResult",
            "value": " "
          },
          {
            "name": "Connect_status",
            "type": "commandStatus",
            "value": "UNKNOWN"
          },
          {
            "name": "MoveDrone_info",
            "type": "commandResult",
            "value": " "
          },
          {
            "name": "MoveDrone_status",
            "type": "commandStatus",
            "value": "UNKNOWN"
          },
          {
            "name": "MoveHands_info",
            "type": "commandResult",
            "value": " "
          },
          {
            "name": "MoveHands_status",
            "type": "commandStatus",
            "value": "UNKNOWN"
          },
          {
            "name": "Talk_info",
            "type": "commandResult",
            "value": " "
          },
          {
            "name": "Talk_status",
            "type": "commandStatus",
            "value": "PENDING",
            "metadatas": [
              {
                "name": "TimeInstant",
                "type": "DateTime",
                "value": "2019-08-27T06:27:40.00Z"
              }
            ]
          },
          {
            "name": "TimeInstant",
            "type": "DateTime",
            "value": "2019-08-28T01:44:17.00Z"
          },
          {
            "name": "abs",
            "type": "Number",
            "value": 1
          },
          {
            "name": "battery",
            "type": "Number",
            "value": 29,
            "metadatas": [
              {
                "name": "TimeInstant",
                "type": "DateTime",
                "value": "2019-08-27T06:36:39.00Z"
              }
            ]
          },
          {
            "name": "category",
            "type": "string",
            "value": "Robot",
            "metadatas": [
              {
                "name": "TimeInstant",
                "type": "DateTime",
                "value": "2019-08-28T01:44:17.00Z"
              }
            ]
          },
          {
            "name": "droneTakeoff",
            "type": "None",
            "value": null
          },
          {
            "name": "guidanceRequest",
            "type": "None",
            "value": null
          },
          {
            "name": "guide_info",
            "type": "commandResult",
            "value": " "
          },
          {
            "name": "guide_status",
            "type": "commandStatus",
            "value": "UNKNOWN"
          },
          {
            "name": "name",
            "type": "String",
            "value": "ユニボ1F案内用",
            "metadatas": [
              {
                "name": "TimeInstant",
                "type": "DateTime",
                "value": "2019-08-28T01:44:17.00Z"
              }
            ]
          },
          {
            "name": "refCamera",
            "type": "Relationship",
            "value": "urn:ngsi-ld:Camera:2",
            "metadatas": [
              {
                "name": "TimeInstant",
                "type": "DateTime",
                "value": "2019-08-28T01:44:17.00Z"
              }
            ]
          },
          {
            "name": "refFloor",
            "type": "Relationship",
            "value": "urn:ngsi-ld:Floor:1",
            "metadatas": [
              {
                "name": "TimeInstant",
                "type": "DateTime",
                "value": "2019-08-28T01:44:17.00Z"
              }
            ]
          },
          {
            "name": "refSpace",
            "type": "Relationship",
            "value": "urn:ngsi-ld:Space:1",
            "metadatas": [
              {
                "name": "TimeInstant",
                "type": "DateTime",
                "value": "2019-08-28T01:44:17.00Z"
              }
            ]
          },
          {
            "name": "status",
            "type": "Text",
            "value": "Ready"
          },
          {
            "name": "thetaX",
            "type": "Number",
            "value": 0
          },
          {
            "name": "thetaY",
            "type": "Number",
            "value": 1
          },
          {
            "name": "x",
            "type": "Number",
            "value": 0.5
          },
          {
            "name": "y",
            "type": "Number",
            "value": 0.37
          },
          {
            "name": "z",
            "type": "Number",
            "value": 0
          }
        ]
      },
      "statusCode": {
        "code": "200",
        "reasonPhrase": "OK"
      }
    }
  ]
}
```

Log message like below:
```log:text
cygnus-elasticsearch-8fbc6dd5b-7kbwr cygnus-elasticsearch time=2019-08-28T01:44:18.886Z | lvl=INFO | corr=5948c2fc-c935-11e9-8ff9-4ee7f3fb241d | trans=d71c2557-e64f-4bef-ba3f-58244135f2cc | srv=roboticbase | subsrv=/ | comp=cygnus-ngsi | op=getEvents | msg=com.telefonica.iot.cygnus.handlers.NGSIRestHandler[294] : [NGSIRestHandler] Starting internal transaction (d71c2557-e64f-4bef-ba3f-58244135f2cc)
cygnus-elasticsearch-8fbc6dd5b-7kbwr cygnus-elasticsearch time=2019-08-28T01:44:18.890Z | lvl=INFO | corr=5948c2fc-c935-11e9-8ff9-4ee7f3fb241d | trans=d71c2557-e64f-4bef-ba3f-58244135f2cc | srv=roboticbase | subsrv=/ | comp=cygnus-ngsi | op=getEvents | msg=com.telefonica.iot.cygnus.handlers.NGSIRestHandler[312] : [NGSIRestHandler] Received data ({"subscriptionId":"5d64c7d48e7ee6dc2b62c21c","originator":"localhost","contextResponses":[{"contextElement":{"type":"Unibo","isPattern":"false","id":"urn:ngsi-ld:Unibo:1","attributes":[{"name":"Alert_info","type":"commandResult","value":" "},{"name":"Alert_status","type":"commandStatus","value":"PENDING","metadatas":[{"name":"TimeInstant","type":"DateTime","value":"2019-08-28T01:44:17.00Z"}]},{"name":"Connect_info","type":"commandResult","value":" "},{"name":"Connect_status","type":"commandStatus","value":"UNKNOWN"},{"name":"MoveDrone_info","type":"commandResult","value":" "},{"name":"MoveDrone_status","type":"commandStatus","value":"UNKNOWN"},{"name":"MoveHands_info","type":"commandResult","value":" "},{"name":"MoveHands_status","type":"commandStatus","value":"UNKNOWN"},{"name":"Talk_info","type":"commandResult","value":" "},{"name":"Talk_status","type":"commandStatus","value":"PENDING","metadatas":[{"name":"TimeInstant","type":"DateTime","value":"2019-08-27T06:27:40.00Z"}]},{"name":"TimeInstant","type":"DateTime","value":"2019-08-28T01:44:17.00Z"},{"name":"abs","type":"Number","value":1},{"name":"battery","type":"Number","value":29,"metadatas":[{"name":"TimeInstant","type":"DateTime","value":"2019-08-27T06:36:39.00Z"}]},{"name":"category","type":"string","value":"Robot","metadatas":[{"name":"TimeInstant","type":"DateTime","value":"2019-08-28T01:44:17.00Z"}]},{"name":"droneTakeoff","type":"None","value":null},{"name":"guidanceRequest","type":"None","value":null},{"name":"guide_info","type":"commandResult","value":" "},{"name":"guide_status","type":"commandStatus","value":"UNKNOWN"},{"name":"name","type":"String","value":"ユニボ1F案内用","metadatas":[{"name":"TimeInstant","type":"DateTime","value":"2019-08-28T01:44:17.00Z"}]},{"name":"refCamera","type":"Relationship","value":"urn:ngsi-ld:Camera:2","metadatas":[{"name":"TimeInstant","type":"DateTime","value":"2019-08-28T01:44:17.00Z"}]},{"name":"refFloor","type":"Relationship","value":"urn:ngsi-ld:Floor:1","metadatas":[{"name":"TimeInstant","type":"DateTime","value":"2019-08-28T01:44:17.00Z"}]},{"name":"refSpace","type":"Relationship","value":"urn:ngsi-ld:Space:1","metadatas":[{"name":"TimeInstant","type":"DateTime","value":"2019-08-28T01:44:17.00Z"}]},{"name":"status","type":"Text","value":"Ready"},{"name":"thetaX","type":"Number","value":0},{"name":"thetaY","type":"Number","value":1},{"name":"x","type":"Number","value":0.5},{"name":"y","type":"Number","value":0.37},{"name":"z","type":"Number","value":0}]},"statusCode":{"code":"200","reasonPhrase":"OK"}}]})
cygnus-elasticsearch-8fbc6dd5b-7kbwr cygnus-elasticsearch time=2019-08-28T01:44:18.983Z | lvl=INFO | corr=5967f2e4-c935-11e9-9e8e-4ee7f3fb241d | trans=5b1b949a-7a0d-4ca7-9192-49914dd84e21 | srv=roboticbase | subsrv=/ | comp=cygnus-ngsi | op=getEvents | msg=com.telefonica.iot.cygnus.handlers.NGSIRestHandler[294] : [NGSIRestHandler] Starting internal transaction (5b1b949a-7a0d-4ca7-9192-49914dd84e21)
cygnus-elasticsearch-8fbc6dd5b-7kbwr cygnus-elasticsearch time=2019-08-28T01:44:18.984Z | lvl=INFO | corr=5967f2e4-c935-11e9-9e8e-4ee7f3fb241d | trans=5b1b949a-7a0d-4ca7-9192-49914dd84e21 | srv=roboticbase | subsrv=/ | comp=cygnus-ngsi | op=getEvents | msg=com.telefonica.iot.cygnus.handlers.NGSIRestHandler[312] : [NGSIRestHandler] Received data ({"subscriptionId":"5d64c7d48e7ee6dc2b62c21c","originator":"localhost","contextResponses":[{"contextElement":{"type":"Event","isPattern":"false","id":"urn:ngsi-ld:Event:twitter.event.fire:OpenData","attributes":[{"name":"event","type":"StructuredValue","value":{"type":"OpenData","name":"twitter.event.fire","entityId":""}},{"name":"eventAt","type":"Text","value":"2019-08-28T01:44:12.192917Z"},{"name":"notifications","type":"StructuredValue","value":[{"notificationType":"User","successCount":2,"failureCount":2,"detail":{"successDetailInfomations":[{"userId":"robo","type":"TEL"},{"userId":"robo","type":"TEL"}],"failureDetailInfomations":[{"userId":"robo","type":"MAIL"},{"userId":"robo","type":"MAIL"}]}},{"notificationType":"Device","successCount":2,"failureCount":0,"detail":{"successDeviceNotifiers":[{"id":{"value":2,"assigned":true},"fromEventName":"twitter.event.fire","entityId":"urn:ngsi-ld:Unibo:1","entityType":"Unibo","command":"Alert","parameters":[],"applying":true,"createdBy":"robo","createdAt":"2019-08-27T06:23:43.619371","updatedBy":"robo","updatedAt":"2019-08-27T06:23:43.619377"},{"id":{"value":4,"assigned":true},"fromEventName":"twitter.event.fire","entityId":"urn:ngsi-ld:Unibo:1","entityType":"Unibo","command":"Alert","parameters":[],"applying":true,"createdBy":"robo","createdAt":"2019-08-27T06:27:45.614836","updatedBy":"robo","updatedAt":"2019-08-27T06:27:45.614841"}],"failureDeviceNotifiers":[]}}]}]},"statusCode":{"code":"200","reasonPhrase":"OK"}}]})
cygnus-elasticsearch-8fbc6dd5b-7kbwr cygnus-elasticsearch time=2019-08-28T01:44:20.083Z | lvl=INFO | corr=5967f2e4-c935-11e9-9e8e-4ee7f3fb241d | trans=5b1b949a-7a0d-4ca7-9192-49914dd84e21 | srv=roboticbase | subsrv=/ | comp=cygnus-ngsi | op=processNewBatches | msg=com.telefonica.iot.cygnus.sinks.NGSISink[590] : Finishing internal transaction (5967f2e4-c935-11e9-9e8e-4ee7f3fb241d)
cygnus-elasticsearch-8fbc6dd5b-7kbwr cygnus-elasticsearch time=2019-08-28T01:44:20.084Z | lvl=ERROR | corr=5948c2fc-c935-11e9-8ff9-4ee7f3fb241d | trans=d71c2557-e64f-4bef-ba3f-58244135f2cc | srv=roboticbase | subsrv=/ | comp=cygnus-ngsi | op=run | msg=org.apache.flume.SinkRunner$PollingRunner[160] : Unable to deliver event. Exception follows.
cygnus-elasticsearch-8fbc6dd5b-7kbwr cygnus-elasticsearch java.lang.NullPointerException
cygnus-elasticsearch-8fbc6dd5b-7kbwr cygnus-elasticsearch  at com.telefonica.iot.cygnus.sinks.NGSIElasticsearchSink$ElasticsearchAggregator.aggregateAsColumn(NGSIElasticsearchSink.java:643)
cygnus-elasticsearch-8fbc6dd5b-7kbwr cygnus-elasticsearch  at com.telefonica.iot.cygnus.sinks.NGSIElasticsearchSink$ElasticsearchAggregator.aggregate(NGSIElasticsearchSink.java:552)
cygnus-elasticsearch-8fbc6dd5b-7kbwr cygnus-elasticsearch  at com.telefonica.iot.cygnus.sinks.NGSIElasticsearchSink.persistBatch(NGSIElasticsearchSink.java:458)
cygnus-elasticsearch-8fbc6dd5b-7kbwr cygnus-elasticsearch  at com.telefonica.iot.cygnus.sinks.NGSISink.processNewBatches(NGSISink.java:558)
cygnus-elasticsearch-8fbc6dd5b-7kbwr cygnus-elasticsearch  at com.telefonica.iot.cygnus.sinks.NGSISink.process(NGSISink.java:370)
cygnus-elasticsearch-8fbc6dd5b-7kbwr cygnus-elasticsearch  at org.apache.flume.sink.DefaultSinkProcessor.process(DefaultSinkProcessor.java:68)
cygnus-elasticsearch-8fbc6dd5b-7kbwr cygnus-elasticsearch  at org.apache.flume.SinkRunner$PollingRunner.run(SinkRunner.java:147)
cygnus-elasticsearch-8fbc6dd5b-7kbwr cygnus-elasticsearch  at java.lang.Thread.run(Thread.java:748)
```

### PR DESCRIPTION
**Pull request by nmatsui**
fix #1838

### CODE REVIEW

File: cygnus-ngsi/src/main/java/com/telefonica/iot/cygnus/sinks/NGSIElasticsearchSink.java [hunk 1]
```diff
@@ -607,7 +607,7 @@ private void aggregateAsRow(long notifiedRecvTimeTs, String entityId, String ent
                 String attrMetadata = contextAttribute.getContextMetadata();
```
Comment (fgalan) [inline cygnus-ngsi/src/main/java/com/telefonica/iot/cygnus/sinks/NGSIElasticsearchSink.java]: An entry to CHANGES_NEXT_RELEASE file, briefly describing the modifications in this PR and referencing the issue number, should be included. Please have a look to existing CHANGES_NEXT_RELEASE file to see the style we use.

Comment (fgalan) [reply cygnus-ngsi/src/main/java/com/telefonica/iot/cygnus/sinks/NGSIElasticsearchSink.java]: Fixed in 3c290ad
